### ISSUE TITLE
Can't invite new contrib account. Expected sequence is not correct.

### ISSUE THREAD

**Issue by kwunyeung** [forbole/forboled#1]
When I run the following command on fb-0

`fbcli contrib --chain-id=forbole-0 --content=496e7669746520746f206a6f696e --name=fb-0 --key=6162636465666768696a6b --type=Invite --home=/forbole/fbcli --sequence=0 --to=9375B5FED33DF7EDA37EAEFD30E3CA5E8B260460 --time=2018-06-01T09:38:46Z`

It gives me the following error.

`Defaulting to next sequence number: 1
Password to sign with 'fb-0':
ERROR: CheckTx failed: (65539) === ABCI Log ===
Codespace: 1
Code:      3
ABCICode:  65539
Error:     --= Error =--
Message: Invalid sequence. Got 1, expected 0
Cause: <nil>
T: 0x3
Msg Traces:
--= /Error =--

=== /ABCI Log ===`

**Comment by ipchikin** [comment]
please pull the latest code from master, it was fixed already
